// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/api/links.ts";
import * as $1 from "./routes/api/title.ts";
import * as $2 from "./routes/contact.tsx";
import * as $3 from "./routes/index.tsx";

const manifest = {
  routes: {
    "./routes/api/links.ts": $0,
    "./routes/api/title.ts": $1,
    "./routes/contact.tsx": $2,
    "./routes/index.tsx": $3,
  },
  islands: {},
  baseUrl: import.meta.url,
  config,
};

export default manifest;
